### ISSUE TITLE
Media links broken in demo (minio-stored 3rd party bags)

### ISSUE THREAD

**Issue by sv-laurent** [AMZ-Driverless/rbb_core#4]
# Setup
I just brought up the local stack with `docker compose`, then downloaded the AMZ bag from `third party bags`. After it was processed, I went to check it out.

# Observed behaviour
It looks like the `api` correctly `302`s to the minio bucket, but the links seem broken. Indeed, accessing those links in my browser essentially returns a "couldn't find server". I'm guessing the `minio.rbb.localhost:9000` doesn't resolve.  
I've checked the files, they do exist (i.e. the bag was processed correctly). I can verify this by removing the `minio.rbb.` part of the URL (while logged in to the minio interface), this sends me to the correct file. Maybe I missed something in the API setup?
![image](https://user-images.githubusercontent.com/58848352/70795804-f32ce500-1da0-11ea-92ff-208faa9a0975.png)

**Comment by sv-laurent** [comment]
I've investigated a bit more, this is specifically linked to my using the demo. The hostname `minio.rbb.localhost` is actually an alias originating from the `docker-compose.yaml`. However, the requests in my browser happen outside of the docker compose bridge, so `minio.rbb.localhost` can't be resolved.

I've fixed it by temporarily adding the following line to my `/etc/hosts`:
```
127.0.0.1 minio.rbb.localhost
```

I'm guessing this could be fixed somewhere in swagger but I don't know exactly where unless the maintainers can give me a few pointers?

**Comment by hfchendrikx** [comment]
Hi, Good that you found a solution :)

This is actually a flaw in the test setup. Some linux distributions have the DNS configured such that `*.localhost` always gets resolved to `127.0.0.1`, this setup relies on that. Turns out that this is way less often the case than I initially thought.

The solution you came up with is a good alternative. I'll adapt the readme and add it there.

Thanks,

Huub

**Comment by sv-laurent** [comment]
I'm indeed running this under macOS so that's what probably kicked off the issue. Otherwise it works a charm though!
